// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/Drive.h"
#include <frc/smartdashboard/SmartDashboard.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Drive::Drive(){
    SetName("Drive");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("Drive");

 AddChild("Mecanum Drive 1", &m_mecanumDrive1);
 m_mecanumDrive1.SetSafetyEnabled(true);
m_mecanumDrive1.SetExpiration(0.1_s);
m_mecanumDrive1.SetMaxOutput(1.0);


 AddChild("LeftBack", &m_leftBack);
 m_leftBack.SetInverted(false);

 AddChild("LeftFront", &m_leftFront);
 m_leftFront.SetInverted(false);

 AddChild("RightBack", &m_rightBack);
 m_rightBack.SetInverted(false);

 AddChild("RightFront", &m_rightFront);
 m_rightFront.SetInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Drive::Periodic() {
    // Put code here to be run every loop

}

void Drive::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.
