// RobotBuilder Version: 6.1
//
// This file was partially generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.Command;
import java.util.function.DoubleSupplier;

//motors



//limelight stuff
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;

//import com.revrobotics.CANsparkmotor; //just in case




// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class com_autonomous extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public com_autonomous() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        // m_subsystem = subsystem;
        // addRequirements(m_subsystem);    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {

float speed = 0.5; //motor speed: BETWEEN -1 and 1

 //limelight variable
double Tx = LimelightHelpers.getTX("");

NetworkTable table = NetworkTableInstance.getDefault().getTable("limelight");
NetworkTableEntry tx = table.getEntry("tx"); //deg in x axis
NetworkTableEntry ty = table.getEntry("ty"); //deg in y axis
NetworkTableEntry area = table.getEntry("area"); //area of screen
NetworkTableEntry tl = table.getEntry("tl"); //distance from ll

//brand spanking new spark controllers
Spark frontleftspark = new Spark(0);
Spark frontrightspark = new Spark(1);
Spark backleftspark = new Spark(2);
Spark backrightspark = new Spark(3);

//read values periodically
double x = tx.getDouble(0.0);
double y = ty.getDouble(0.0);
double ta = Ta.getDouble(0.0);

//post to smart dashboard periodically
SmartDashboard.putNumber("LimelightX", x);
SmartDashboard.putNumber("LimelightY", y);
SmartDashboard.putNumber("LimelightArea", area);
SmartDashboard.putNumber("LimelightL", tl);

//go forwards
frontleftspark.set(speed); 
backleftspark.set(speed); 
frontrightspark.set(speed); 
backrightspark.set(speed); 


println("tl =");
println(tl);

//turn to tag
while (tx < -1) { //number tx compared to is deadzone: used for tuning

frontrightspark.set(speed);
backrightspark.set(speed);
frontleftspark.set(speed + 0.1);
backleftspark.set(speed + 0.1); //tune values later
}

//also, turn to tag
while (tx < -1) { //number tx compared to is deadzone: used for tuning

frontleftspark.set(speed);
backleftspark.set(speed);
frontrightspark.set(speed + 0.1);
backrightspark.set(speed + 0.1); //tune values later
}

while (1 > tx > -1) {



}
    
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
